version: '3.7'

services:
  mysql:  
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    restart: unless-stopped
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password

  gateway:
    build: ./lumen-api-gateway
    container_name: gateway
    hostname: gateway
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "8001:80"
    depends_on:
      - mysql
  
  authors:
    build: ./lumen-authors-api
    container_name: authors
    hostname: authors
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "8002:80"
    depends_on:
      - mysql
  
  authors:
    build: ./lumen-books-api
    container_name: books
    hostname: books
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "8003:80"
    depends_on:
      - mysql

secrets:
  db_root_password:
    file: db_root_password.txt
  db_password:
    file: db_password.txt

volumes:
  mysql-data:

networks:
  default:
